// Generated by CoffeeScript 1.6.3
$(function() {
  var userAgent, view;
  userAgent = window.navigator.userAgent;
  view = {
    render: function(ua) {
      return $("#user-agent").text(ua);
    }
  };
  return view.render(userAgent);
});
